# permissions for end users to view operatordemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatordemo-viewer-role
rules:
- apiGroups:
  - demo.my.domain
  resources:
  - operatordemoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.my.domain
  resources:
  - operatordemoes/status
  verbs:
  - get
