# permissions for end users to edit operatordemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatordemo-editor-role
rules:
- apiGroups:
  - demo.my.domain
  resources:
  - operatordemoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.my.domain
  resources:
  - operatordemoes/status
  verbs:
  - get
